# Generated by Django 5.2.8 on 2026-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_user_display_name_user_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
