# Generated by Django 5.2.8 on 2026-04-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_user_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='generation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='generation_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='generation_status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='IDLE', max_length=16),
        ),
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musicgenerationrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
